### ISSUE TITLE
Missing explaination meta data in business models applications

### ISSUE THREAD

**Issue by Cudok** [TUB-DVG/wissen-digital-ewb#128]
## Description of the issue

at the site of the business models applications the explanation of the meta data are missing.
![image](https://github.com/user-attachments/assets/7340e66f-9470-41f7-b62b-cb1a5a66d913)

## Steps to Reproduce

1. open https://wissen-digital-ewb.de/en/tool_list/businessApps/
2. compare with explain text from  https://wissen-digital-ewb.de/en/tool_list/

## Ideas of solution
also the business model has the same structure than digital tools and applications

## Workflow checklist

- [ ] check are the meta data fields the same as for digital tools
- [ ] choose the needed meta data fields
- [ ] check is the meaning of the meta data fields the same
- [ ] copy the regarding fields in to the html code
- [ ] check the page
- [ ] if meta data field missing or have an other meaning, bring discussion into next jour fix
